### ISSUE TITLE
UTHMise the System

### ISSUE THREAD

**Issue by Zyten** [Zyten/simple-mpp-election#1]
Update all static information to reflect on UTHM.

**Comment by Zyten** [comment]
@wqyap762  Here

**Comment by wqyap762** [comment]
This is the one I need to do?

**Comment by Zyten** [comment]
It wasn't but now it is. Haha. You can checkout all issues assigned to you by adding search filters.
However to be honest, the assignments are not rock solid. Just pick any issues that you want to work on and comment there saying you are doing it.
